### ISSUE TITLE
Zoom on iphone

### ISSUE THREAD

**Issue by Senthilmj** [waynegm/imgViewer#14]
i am implemented imgView for zoom the image in my website it's work well.. but in iphone body scroll with the zoom..someone can fix this

**Comment by waynegm** [comment]
Maybe too late for you but I have made a lot of changes to improve the mobile experieince in the master branch preparing for a 1.0.0 release and I think I may have fixed this but don't have an iOS device to verify for certain. If it;s still a problem please reopen the issue.
