### ISSUE TITLE
Question about saving to image

### ISSUE THREAD

**Issue by ProcSIMus** [waynegm/imgViewer#15]
Hi Wayne,

Sorry to use this channel to send you a question about imgViewer. This is not an issue but I couldn't find any other appropriate place to ask you this.

Do you somehow know a way to save the image with added markers to an image or base64 encoded string (directly). I have to save the images for reporting purposes and now use a very complicated way with screenschots. I also tried to use html2canvas like this:

                        $(document).ready(function () {
                            html2canvas($img.imgNotes(), {
                                onrendered: function (canvas) {
                                     canvas.toBlob(function (blob) {
                                      saveAs(blob, "marker_image.png");
                                    });
                                }
                            })
                        });

This only saves the image and not the markers. If you could provided me with a solution/suggestion here I would be very thankfull.

Best regards,
Richard

**Comment by waynegm** [comment]
Have a look at the file in the imgNotes examples folder called "basic_interactive.html" which implements a button to print the image and note markers using the browser print facility. This combines a plugin called [printThis](https://github.com/jasonday/printThis) and some modified css in a custom onAdd callback to make the markers visible. You could also try this callback with your html2canvas code as I recall the markers produced by the default onAdd callback wouldn't print so maybe it's a common problem.
