### ISSUE TITLE
IE11 not returning a position

### ISSUE THREAD

**Issue by tjpa** [waynegm/imgViewer#16]
I noticed the problem first in ImgNotes when creating a new marker.
It seems that from 0.8.0 the clicked position isn't returned.
It can be reproduced using the demo.html and pageX/pageY are NaN.

**Comment by waynegm** [comment]
Don't have IE11 available but this may be a problem with the library I use to support touch and mouse events (Hammerjs). I'll see if I can scrounge some time on a Window's box to work out what is going on. Actually thinking about changing the widget to use the Leaflet mapping widget. Updates for that seem to be more regular while Hammerjs seems to not be very active now.

**Comment by waynegm** [comment]
This should be fixed along with a lot other issues in the master branch. If not please reopen.
