### ISSUE TITLE
Panning not working, zoomin does, where should I look for the problem?

### ISSUE THREAD

**Issue by markkap** [waynegm/imgViewer#17]
Sorry not publicly available page, just not sure what to look for at all.

Problem on firefox,chrome,edge, zooming and panning with a laptops touchpad.
Are there any special properties that the containing element should not have or any other limitation?

**Comment by waynegm** [comment]
I use HammerJs for the touch support. Can you visit [http://hammerjs.github.io/](http://hammerjs.github.io/) and let me know if the touchpad works on their examples.

**Comment by markkap** [comment]
Your demo sites work for both zooming and panning, which is why I am sure there is something wrong on my end :( should I get any error if hammer failed to initialize properly?

**Comment by waynegm** [comment]
The demo site is using version 0.9.0 of the widget and version 2.0.1 of HammerJs. I have made some changes to the GitHub master to add  a zoomMax option. That was only a minor change and shouldn't have broken anything but you never know. I've also found the later versions of HammerJs have issues. 

Download the ghpages branch and give the libs/imgViewer.min.js in there a go.

Another thing to check would be if panning generates any console errors. You can also send me the code where you are using the plugin - maybe I will spot the issue.

**Comment by markkap** [comment]
grrr, resolved. decided to try and understand hammer and found out that I don't see where the imgviewer intercepts the pan event.... so went back to look at the source on github an saw it there.... bottom line, not sure what exactly I have downloaded at first, but obviously it wasn't the latest release.

Anyway, thanks for this nice utility (and the imgNote which is the actual reason for me to use it) and for your time trying to help here.
