### ISSUE TITLE
blocked row/column of pixel

### ISSUE THREAD

**Issue by Obras** [waynegm/imgViewer#19]
Hi.

Not even sure if it's worth mentioning, but I found that, using dynamic pictures, sometimes a row and/or column of pixels from the original image stays blocked in the bottom and/or right edge of the pan/zoom area. This is a screenshot taken from the demo, where you can see the problem on right and bottom edge

![schermata 2017-07-17 alle 12 41 49](https://user-images.githubusercontent.com/11693174/28265719-818cb8d0-6af1-11e7-8158-13d4ae8ad4ab.png)

This glitch disappears after a simple window resize, so actually I resolved hiding the element parent at page loading, forcing a resize event with
```
$(window).resize();
```
and then displaying the image container again.

Thanks!

**Comment by waynegm** [comment]
I've seen that occasionally too but haven't been able to isolate where the problem is. It doesn't seem to happen when yo use the debugger which makes finding the problem a challenge. Glad you found a work around.

**Comment by Obras** [comment]
Ah, it makes sense to me, since opening the debugger tools usually causes a window resize. Have you ever tried to detach the debug window and the force-reloading the page? In my tests that allows to avoid the resize, so giving the opportunity of getting to the debugger while looking at the problem.

**Comment by waynegm** [comment]
I got this to work properly by wrapping the $(document).ready callback in the examples in a $(window).on("load") callback. The plugin needs to know the image size in the DOM when it is initialised. Trouble is the image appears to be resized after the on load event for the image is triggered.  Putting everything in a $(window).on("load") callback ensures everything is loaded and sizes are stable when the plugin is initialized.
