### ISSUE TITLE
How to set scroll direction to increase or decrease zoom

### ISSUE THREAD

**Issue by tonibytecode** [waynegm/imgViewer#23]
how can i control scrollUp (+) set zoom (+) with mouse?
actually work scrollDown(-) set zoom(+)  and scrollUp set zoom(-) on image,
 I need the opposite configuration, please help me.

**Comment by waynegm** [comment]
When you construct the viewer set the zoomStep option to a negative number eg:
```
<script type="text/javascript">
;(function($) {
    $(window).on("load", function() {
		var $img = $("#image1").imgViewer({zoomStep: -0.1});
	});
})(jQuery);
</script>
```

**Comment by tonibytecode** [comment]
thanks. its worked!!
