### ISSUE TITLE
Minimap navigator?

### ISSUE THREAD

**Issue by mofman** [waynegm/imgViewer#4]
Just wondering how difficult it would be to implement a little minimap navigator to your viewer wayne? 
Heres an example of what I'm talking about http://webcraft.cc/product.php?product=uber-zoom

**Comment by waynegm** [comment]
You can do most of that using the hooks exposed by the plugin, even panning of the image by moving the highlight box. I've added an example to the [demo page](http://waynegm.github.io/imgNotes/examples/with_overview.html). Apologies for the unpolished coding style but at least it works.

**Comment by waynegm** [comment]
Oops - just realised this is the imgViewer issue page. The example I've made is actually for the imgNotes plugin. Is that a problem?

**Comment by mofman** [comment]
Not a problem at all Wayne, the demo looks great. I'll play about with it
on Monday! Nice work!

**Comment by grubbychicken** [comment]
Hi Wayne! Sorry, me again!

just wondering if this minimap/overview example code exists somewhere?  Your link is broken.
I quite like the sounds of this feature!
Thanks!

**Comment by waynegm** [comment]
It should be in the examples folder of this [previous release](https://github.com/waynegm/imgNotes/releases/tag/0.9.1)
