### ISSUE TITLE
Image extends over containing div

### ISSUE THREAD

**Issue by anuragji** [waynegm/imgViewer#5]
Hello,

First of all, thanks for the great tool!

I have implemented  it into one project,  but I am ecountering an issue, where the zoom image, upon initial pageload, extends over the containing div, like this:

![imgviewer_01_initialload](https://cloud.githubusercontent.com/assets/5738275/7990179/339253ce-0abd-11e5-98b4-9d848a65bc88.png)

Once I hover over the image, or refresh the page, it sets itself correctly:

![imgviewer_02_afterrefresh](https://cloud.githubusercontent.com/assets/5738275/7990201/5b5b1b66-0abd-11e5-8e1a-594fd0fd3d92.png)

I tried to simply `toggle()` the containing div, as a refresh, but that does not seem to work.

It actually looks like the image is overlayed incorrectly, as sometimes, on the bottom, you see two images:

![imgviewer_03_incorrectoverlay](https://cloud.githubusercontent.com/assets/5738275/7990498/6d709568-0abf-11e5-8ffa-f8229ec083de.png)

Do you have any idea as to how to resolve this issue?

**Comment by waynegm** [comment]
It could be related to css styling applied to the image. Any chance you can provide access to a standalone example with the problem or a link to a test page I can take a look at.

Cheers Wayne.

**Comment by anuragji** [comment]
Dear Wayne,

Thanks, that would be great. Examples would be:

http://ww1mproject.org/items/show/82
http://ww1mproject.org/items/show/81
http://ww1mproject.org/items/show/80

It seems to affect desktop browsers more so than mobile.

All the best,

Anurag 

> It could be related to css styling applied to the image. Any chance you can provide access to a standalone example with the problem or a link to a test page I can take a look at.
> 
> Cheers Wayne
>

**Comment by waynegm** [comment]
Anurag,
Had a look using the latest  version of Chrome and Firefox on Linux, Firefox on Windows and on an android tablet and your pages load fine. What browser/version are you testing with?

Wayne

**Comment by anuragji** [comment]
I am using the latest versions as well. I just checked my DEV server and 
the issue does occur there.

For example : http://wwidev.digark.net/items/show/83

**Comment by waynegm** [comment]
Had a look at work using Windows+Firefox using your last link and did see the issue but can't see it at home on my linux machine or a Windows virtual machine even tried clearing the browser cache to force a complete reload. I'll try again at work tomorrow.

**Comment by waynegm** [comment]
OK I've been able to get the problem by using the network emulation option in Chrome. The problem appears for slower networks. In my case emulating a 2G network caused all sorts of problems. Initial thought is that your page hasn't finished loading when the imgViewer is trying to set things up.  Could you try moving the $(".zoomImg").imgViewer(); line into the  $(document).ready(function().

**Comment by anuragji** [comment]
Thank you so much for taking all this time to look at the issue. Yes, that appears to have solved the problem. I think it was my mistake thinking that `(function($) {...}) (jQuery);` and `$(document).ready(function() {...});` are really the same.

**Comment by waynegm** [comment]
No worries - good luck with your website - you got some really cool photos and content.

**Comment by anuragji** [comment]
Thanks! We are getting the site ready for a big grant application to keep it funded.
