### ISSUE TITLE
URGENT: Not zooming to the actual area

### ISSUE THREAD

**Issue by goelsid** [waynegm/imgViewer#7]
When we are zooming, the img is not zooming correctly. Instead, it gets shifted to right or left. Essentially, on a pinch zoom, the center area(i.e. the area between 2 fingers) should be the one that should come zoomed out. The image is shifting and the user has to go and dot eh panning manually to arrive at the original pinched position.

This is applicable in your demos also. Is this already an known issue and has somebody reported this as well.

**Comment by waynegm** [comment]
It is an issue I was aware of but I haven't been able to find a way to debug multi-touch events so I can isolate the problem and fix it. I'll have another look but I can't make any promises.

**Comment by waynegm** [comment]
OK I tracked down the problem to drag events being triggered when doing a pinch gesture. I've made some changes which improve the pinch gesture behaviour. The changes have been pushed to Master and the demos. Please have a look and let me know if this resolves he issue for you.

**Comment by waynegm** [comment]
Closing this issue assuming no response means all ok..

**Comment by goelsid** [comment]
Wayne,

The pinch zoom has become smoother but the zoom still works from center of
the image and not from..where you zoomed.

Regards,
Sidharth.
