### ISSUE TITLE
Zoom in Zoom out 

### ISSUE THREAD

**Issue by ashwinkalyanpur** [waynegm/imgViewer#8]
![capture2](https://cloud.githubusercontent.com/assets/3168749/12973222/d53e1ad0-d0d0-11e5-8d6c-4de639ad7571.PNG)
HI waynegm,
I am using your plugin its really awesome thanks.
Going ahead  add feature as like image slide with your edit, save marking, add comments, next and previous slide.
A very much thank you.
But wanted small help like i have two icons for zoom in and zoom out can you please help me out to add the functionality for this icon to image zoom in and zoom out as i tried a lot could not achieve for this feature. Please let me know if you have any solution if yes can you please send me the code for my mail id ashwinikumar@regalix-inc.com.

Many Thanks,

Ashwini Kumar

**Comment by waynegm** [comment]
Ashwini,

Its quite simple you just need to adjust the value of the imgNote/imgViewer zoom option. Have a look at the attached file where I've added a zoom and unzoom button. Note you can adjust the amount of zoom change by setting the imgNote/imgViewer zoomStep option.


[temp.html.zip](https://github.com/waynegm/imgViewer/files/126182/temp.html.zip)

**Comment by ashwinkalyanpur** [comment]
Thanks a lot for immediate support

**Comment by ashwinkalyanpur** [comment]
HI waynegm,
one more requirement was on flow i wanted to comperes the image file upload size from 20+ MB file to 1mb or below with out reducing the image size(width and height as height is defined for 500px.

**Comment by waynegm** [comment]
To reduce the file size you have to either change the image height and width or use higher JPG compression. You should do this using the image resize and saveas options in an image editor (eg Irfanview or Gwenview).  For high quality JPG images you will need to resize the image to have around 3 megapixels to get a file size around 1MB. Its hard to be exact because the final size depends on how much image compression/quality loss you use.

**Comment by ashwinkalyanpur** [comment]
Ok thank you will try to do it from image editor or from bac kend code
using JAVA
Thnaks a lot for solution

2016-02-12 18:54 GMT+05:30 Wayne Mogg <notifications@github.com>:

> To reduce the file size you have to either change the image height and
> width or use higher JPG compression. You should do this using the image
> resize and saveas options in an image editor (eg Irfanview or Gwenview).
> For high quality JPG images you will need to resize the image to have
> around 3 megapixels to get a file size around 1MB. Its hard to be exact
> because the final size depends on how much image compression/quality loss
> you use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/waynegm/imgViewer/issues/8#issuecomment-183326630>.
>



-- 
   Ashwini Kumar Kalyanpur
(Web Cum Graphic Designer)
