### ISSUE TITLE
Wanted to close Note Edit

### ISSUE THREAD

**Issue by ashwinkalyanpur** [waynegm/imgViewer#9]
Hi Waynegm,
Thanks for helping for previous issue.
I have one more request for closing of NoteEditor on click of clear button in the tools.
My Mail Id ashwinkalyanpur@hotmail.com
Thanks,

Ashwini Kumar

**Comment by waynegm** [comment]
$('#NoteDialog').remove();

should do the trick

**Comment by ashwinkalyanpur** [comment]
Sorry went through the found this code in imgNotes.js and applied thanks a
lot

2016-03-22 17:28 GMT+05:30 Wayne Mogg <notifications@github.com>:

> $('#NoteDialog').remove();
>
> should do the trick
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/waynegm/imgViewer/issues/9#issuecomment-199778305>
>



-- 
   Ashwini Kumar Kalyanpur
(Web Cum Graphic Designer)

**Comment by ashwinkalyanpur** [comment]
Hello Wayne,
Thanks a lot for previous help i am so great of it.
Have one more question can we display marking number in the image notes which is displayed on the image.

**Comment by waynegm** [comment]
You can do that by defining a custom "onShow" callback. In the example below see the line:
```
$(this).html($elem.text()+ ". "+$elem.data("note"));
```
where I pull the number from the html attached to the marker and then concatenate it and the note together.
```javascript
			onShow: function(ev, elem) {
				var $elem = $(elem);
				$('#NoteDialog').remove();
				return $('<div id="NoteDialog"></div>').dialog({
					modal: false,
					resizable: false,
					height: 300,
					width: 250,
					position: { my: "left bottom", at: "right top", of: elem},
					buttons: {
						"Close" : function() {
							$(this).dialog("close");
						}
					},
					open: function() {
//			Get the note text and put it into the textarea - here I prepend the note number
						$(this).html($elem.text()+ ". "+$elem.data("note"));
						$(this).closest(".ui-dialog").find(".ui-dialog-titlebar:first").hide();
						
					},
					close: function() {
						$(this).dialog("destroy");
					}
				});
			}
````

**Comment by ashwinkalyanpur** [comment]
i am calling this note in my custome JS like 
$table.append("<tr><td style='display:none'>" + item.x + "</td><td style='display:none'>" + item.y + "</td><td>" + item.note + " </td></tr>");
but this is not showing the index numbering can you please let me know how i can call index.
As i i have one more requirement i wanted to update the text(note) on click of save so i can remove the export option.

**Comment by ashwinkalyanpur** [comment]
and also on cancel to remove he notes from the grid

**Comment by waynegm** [comment]
To implement the save you just need to include call clear all the notes and reimport the edited notes:
```
$img.imgNotes('clear')
$img.imgNotes('import',notes)
```
Do the same after deleting a note from the table. The variable notes should contain a javascript array object that looks like this:
```
[ {x: "0.5", y:"0.5", note:"AFL Grand Final Trophy"}, 
  {x: "0.322", y:"0.269", note: "Brisbane Lions Flag"},
  {x: "0.824", y: "0.593", note: "Fluffy microphone"} ]
```
With the note numbering can't you just use a counter in the loop that populates the table:
```
count=1;
$.each(notes, function(index, item) {
    $table.append("<tr><td>" + count + "</td><td>" + item.x + "</td><td>" + item.y + "</td><td>" + item.note + "</td></tr>");
    count++;
});
```
